/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#0b1326",
        foreground: "#dae2fd",
        "primary-fixed-dim": "#b8c8e0",
        "on-primary-fixed-variant": "#39485c",
        "on-tertiary-fixed": "#281801",
        "secondary-container": "#454a4f",
        "surface-container": "#171f33",
        "on-surface": "#dae2fd",
        "surface-tint": "#b8c8e0",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#402d10",
        "surface-dim": "#0b1326",
        "primary": "#b8c8e0",
        "surface-variant": "#2d3449",
        "slate-surface": "#1E293B",
        "matte-charcoal": "#0F172A",
        "inverse-surface": "#dae2fd",
        "inverse-primary": "#515f74",
        "tertiary-fixed": "#feddb4",
        "on-surface-variant": "#c4c6cd",
        "on-tertiary-container": "#38260a",
        "surface-bright": "#31394d",
        "primary-fixed": "#d4e4fc",
        "low-contrast-border": "#334155",
        "error-container": "#93000a",
        "surface": "#0b1326",
        "tertiary-container": "#a88c68",
        "on-secondary-container": "#b4b9bf",
        "on-secondary-fixed": "#171c20",
        "primary-container": "#8392a8",
        "secondary-fixed-dim": "#c3c7cd",
        "on-error": "#690005",
        "steel-blue": "#4A5568",
        "ink-black": "#020617",
        "on-primary-fixed": "#0d1c2e",
        "outline-variant": "#44474c",
        "surface-container-lowest": "#060e20",
        "surface-container-high": "#222a3d",
        "on-secondary-fixed-variant": "#43474c",
        "surface-container-low": "#131b2e",
        "on-primary-container": "#1c2b3d",
        "inverse-on-surface": "#283044",
        "on-background": "#dae2fd",
        "silver-text": "#E2E8F0",
        "outline": "#8e9197",
        "on-secondary": "#2c3136",
        "tertiary-fixed-dim": "#e0c29a",
        "on-primary": "#223144",
        "error": "#ffb4ab",
        "secondary": "#c3c7cd",
        "on-tertiary-fixed-variant": "#584325",
        "secondary-fixed": "#dfe3e9",
        "tertiary": "#e0c29a",
        "surface-container-highest": "#2d3449",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg-mobile": ["'Hanken Grotesk'", "sans-serif"],
        "display-lg": ["'Hanken Grotesk'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "label-md": ["'JetBrains Mono'", "monospace"],
        "mono-sm": ["'JetBrains Mono'", "monospace"],
      },
      spacing: {
        "unit": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "xxl": "96px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}

