/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#FAF8F5",
        foreground: "#0F172A",
        cream: {
          DEFAULT: "#FAF8F5",
          50: "#FDFBF7",
          100: "#FAF8F5",
          200: "#F5F2EB",
          300: "#EAE5DC",
          400: "#DDD6CA",
          500: "#C9BFB0",
          border: "#E8E4DC",
        },
        "brand-blue": {
          50: "#EFF6FF",
          100: "#DBEAFE",
          200: "#BFDBFE",
          300: "#93C5FD",
          400: "#60A5FA",
          500: "#3B82F6",
          600: "#2563EB",
          700: "#1D4ED8",
          800: "#1E40AF",
          900: "#1E3A8A",
        },
        "primary-fixed-dim": "#BFDBFE",
        "on-primary-fixed-variant": "#1E40AF",
        "on-tertiary-fixed": "#1E3A8A",
        "secondary-container": "#F5F2EB",
        "surface-container": "#FFFFFF",
        "on-surface": "#0F172A",
        "surface-tint": "#2563EB",
        "on-error-container": "#7F1D1D",
        "on-tertiary": "#FFFFFF",
        "surface-dim": "#FAF8F5",
        "primary": "#2563EB",
        "surface-variant": "#F5F2EB",
        "slate-surface": "#FFFFFF",
        "matte-charcoal": "#FAF8F5",
        "inverse-surface": "#0F172A",
        "inverse-primary": "#BFDBFE",
        "tertiary-fixed": "#DBEAFE",
        "on-surface-variant": "#475569",
        "on-tertiary-container": "#1E40AF",
        "surface-bright": "#FFFFFF",
        "primary-fixed": "#DBEAFE",
        "low-contrast-border": "#E8E4DC",
        "error-container": "#FEE2E2",
        "surface": "#FFFFFF",
        "tertiary-container": "#EFF6FF",
        "on-secondary-container": "#334155",
        "on-secondary-fixed": "#1E293B",
        "primary-container": "#EFF6FF",
        "secondary-fixed-dim": "#EAE5DC",
        "on-error": "#FFFFFF",
        "steel-blue": "#475569",
        "ink-black": "#0F172A",
        "on-primary-fixed": "#1E3A8A",
        "outline-variant": "#E2DDD5",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-high": "#F5F2EB",
        "on-secondary-fixed-variant": "#475569",
        "surface-container-low": "#FDFBF7",
        "on-primary-container": "#1D4ED8",
        "inverse-on-surface": "#F8FAFC",
        "on-background": "#0F172A",
        "silver-text": "#0F172A",
        "outline": "#94A3B8",
        "on-secondary": "#1E293B",
        "tertiary-fixed-dim": "#BFDBFE",
        "on-primary": "#FFFFFF",
        "error": "#EF4444",
        "secondary": "#F5F2EB",
        "on-tertiary-fixed-variant": "#1E40AF",
        "secondary-fixed": "#F5F2EB",
        "tertiary": "#2563EB",
        "surface-container-highest": "#EAE5DC",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "headline-md": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg-mobile": ["'Hanken Grotesk'", "sans-serif"],
        "display-lg": ["'Hanken Grotesk'", "sans-serif"],
        "body-lg": ["'Inter'", "sans-serif"],
        "body-md": ["'Inter'", "sans-serif"],
        "label-md": ["'JetBrains Mono'", "monospace"],
        "mono-sm": ["'JetBrains Mono'", "monospace"],
      },
      spacing: {
        "unit": "4px",
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "48px",
        "xxl": "96px",
        "container-max": "1440px",
        "gutter": "24px"
      },
      borderRadius: {
        lg: `var(--radius)`,
        md: `calc(var(--radius) - 2px)`,
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}

